server:
  port: 8083

spring:
  application:
    name: psp-paypal-service
  
  data:
    mongodb:
      # Povezivanje na MongoDB kontejner (port 27017)
      # uri: mongodb://username:password@host:port/database?authSource=admin
      uri: mongodb://admin:super@localhost:27017/psp_paypal_db?authSource=admin