server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      
      # Definisanje ruta ka tvojim mikroservisima
      routes:
        # Rute za CORE servis (uključuje transakcije i QR kod)
        - id: core-service
          uri: http://localhost:8081
          predicates:
            - Path=/core/**, /transactions/**, /api/qr/**
          filters:
            - StripPrefix=1 # Ako Angular šalje /core/transactions, skida "core" i gađa direktno /transactions na 8081

        # Rute za BANK servis
        - id: bank-service
          uri: http://localhost:8082
          predicates:
            - Path=/bank/**
          filters:
            - StripPrefix=1

        # Rute za PAYPAL servis
        - id: paypal-service
          uri: http://localhost:8083 # Proveri port svog PayPal servisa
          predicates:
            - Path=/paypal/**
          filters:
            - StripPrefix=1

# Logovanje za lakši debag tokom odbrane
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG