server:
  port: 8081

spring:
  application:
    name: psp-core-service
  
  datasource:
    # Povezujemo se na localhost:5432 jer pokrećeš Java aplikaciju lokalno,
    # a Docker je mapirao port 5432 kontejnera na 5432 tvog računara.
    url: jdbc:postgresql://localhost:5444/psp_core_db
    username: postgres
    password: super
  
  jpa:
    hibernate:
      ddl-auto: update # Ovo će automatski kreirati tabele u bazi na osnovu Java klasa
    show-sql: true # Da vidimo u konzoli šta Hibernate radi
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect